### ISSUE TITLE
modprobe: FATAL: Module edac_core is builtin

### ISSUE THREAD

**Issue by mvernimmen** [Klaas-/ansible-role-disable-edac#1]
Hi Klaas,

With this kernel:
Linux pve-01 5.15.35-2-pve #1 SMP PVE 5.15.35-5 (Wed, 08 Jun 2022 15:02:51 +0200) x86_64 GNU/Linux

I get this error when using the latest version of your ansible role:
```TASK [disable-edac-klaas : unload edac modules] ********************************
ok: [pve-01.of01.textkernel.net] => (item=amd64_edac_mod)
ok: [pve-01.of01.textkernel.net] => (item=e752x_edac)
failed: [pve-01.of01.textkernel.net] (item=edac_core) => {"ansible_loop_var": "item", "changed": false, "item": "edac_core", "msg": "modprobe: FATAL: Module edac_core is builtin.\n", "name": "edac_core", "params": "", "rc": 1, "state": "absent", "stderr": "modprobe: FATAL: Module edac_core is builtin.\n", "stderr_lines": ["modprobe: FATAL: Module edac_core is builtin."], "stdout": "", "stdout_lines": []}
ok: [pve-01.of01.textkernel.net] => (item=edac_mce_amd)
ok: [pve-01.of01.textkernel.net] => (item=i10nm_edac)
ok: [pve-01.of01.textkernel.net] => (item=i3000_edac)
ok: [pve-01.of01.textkernel.net] => (item=i3200_edac)
ok: [pve-01.of01.textkernel.net] => (item=i5000_edac)
ok: [pve-01.of01.textkernel.net] => (item=i5100_edac)
ok: [pve-01.of01.textkernel.net] => (item=i5400_edac)
ok: [pve-01.of01.textkernel.net] => (item=i7300_edac)
ok: [pve-01.of01.textkernel.net] => (item=i7core_edac)
ok: [pve-01.of01.textkernel.net] => (item=i82975x_edac)
ok: [pve-01.of01.textkernel.net] => (item=ie31200_edac)
ok: [pve-01.of01.textkernel.net] => (item=igen6_edac)
ok: [pve-01.of01.textkernel.net] => (item=pnd2_edac)
ok: [pve-01.of01.textkernel.net] => (item=sb_edac)
ok: [pve-01.of01.textkernel.net] => (item=skx_edac)
ok: [pve-01.of01.textkernel.net] => (item=x38_edac)```

Is there a known workaround or fix for this?

**Comment by Klaas-** [comment]
Hi @mvernimmen ,
so the error is that ansible can't unload the module because it's built into the kernel directly. I don't think there is an easy way around that :)
I'd say you have two options to continue, depending on what the outcome is you want to achieve.
1) You can overwrite the variable https://github.com/Klaas-/ansible-role-disable-edac/blob/0803512c84b248f6bebd1351c8cdaabdb86fe858/defaults/main.yml#L5 to not include edac_core - I am not 100% sure if this is still counting as "disabling edac" if that functionality is still in place
2) you need to change the kernel to compile edac_core as module

I am actually not sure if there is a 3) - it could be possible to remove edac_core even though it's not a module, but I am not sure how that works - never tried that :) Also you should keep in mind that your vendor may have built it into kernel directly for a reason. Maybe they require it for their software or something like that.

Greetings
Klaas

**Comment by mvernimmen** [comment]
Hi Klaas,
I've done some tests. With edac_core excluded from the unload list, memory errors are still detected by the lenovo XCC/IMM so that solution works for me.
Thanks!
